In [ ]:
import numpy as np

marks = [60,80,42,63,35,75,95]

avg_marks = (np.mean(marks))
print(avg_marks)

highest_marks = (np.max(marks))
print(highest_marks)

lowest_marks = (np.min(marks))
print(lowest_marks)

marks = np.array(marks)
passed = marks[marks >= 50]
print(passed)

failed = marks[marks < 50]
print(failed)


64.28571428571429
95
35
[60 80 63 75 95]
[42 35]


In [ ]:
#Task:1
import numpy as np
marks = np.array([10, 20, 30, 40, 50])


print(np.sum(marks))
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))

150
30.0
50
10


In [ ]:
#Task:2
import numpy as np
marks = np.array([45, 80, 30, 90, 55, 20])

greatest = marks[marks >= 50]

print(greatest)

[80 90 55]


In [ ]:
# task:3
import numpy as np

marks = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(marks[0,0])

1


In [ ]:
#Task:4
import numpy as np
marks = np.random.randint(40, 100, 10)

print(marks)

print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))

[72 51 92 46 69 44 83 45 55 97]
65.4
97
44


In [ ]:
#Task:5
import numpy as np

marks = np.array([35, 67, 89, 45, 90, 22, 70, 58])
passed = marks[marks >= 50]
failed = marks[marks < 50]

print("\nPassed Students Marks")
print(passed)

print("\nFailed Students Marks")
print(failed)


Passed Students Marks
[67 89 90 70 58]

Failed Students Marks
[35 45 22]


In [ ]:
#Practice

In [ ]:
import numpy as np
data = np.array([
    [10, 35, 45, 44],
    [20, 30, 70, 80]
])

print(data.ndim)
print(data.size)
print(data.dtype)
print(data.shape)


2
8
int64
(2, 4)


In [ ]:
import numpy as np

marks = np.array([33, 78, 66, 89])

print(marks + 5)
print(marks * 2)
print(marks - 3)
print(marks / 2)

[38 83 71 94]
[ 66 156 132 178]
[30 75 63 86]
[16.5 39.  33.  44.5]


In [ ]:
import numpy as np

marks = np.array([10, 20, 30 ,40, 50])

print(marks.size)
print(marks.shape)
print(marks.dtype)



5
(5,)
int64


In [ ]:
import numpy as np

marks = np.array([5, 10, 15, 20, 25])

print(marks +5)
print(marks - 4)
print(marks * 3)
print(marks / 2)

[10 15 20 25 30]
[ 1  6 11 16 21]
[15 30 45 60 75]
[ 2.5  5.   7.5 10.  12.5]


In [ ]:
marks = np.array([10, 15, 20, 25, 30, 35, 40, 45,50])

print(np.max(marks))
print(np.min(marks))
print(np.sum(marks))
print(np.mean(marks))

50
10
270
30.0


In [ ]:
marks = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(marks.shape)
print(marks[1,2])

(3, 3)
6


In [ ]:
import numpy as np

print(np.zeros(8))
print(np.ones(9))

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#arrrange
print(np.arange(1,40))
print(np.arange(2, 40, 3))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[ 2  5  8 11 14 17 20 23 26 29 32 35 38]


In [ ]:
#random
num = np.random.randint(60, 750, 100)

print(num)

[231 429 445  96 688 554 270 244  62 644 134  86 659 529  69 583 386 504
 402 559 423 652 161 168  85  75  91 336 218 122  66 229 691 267 543 388
 404 184 367 108 268 596 313 319 623 483 544 401 201 430 353 453 369 530
 730 483  91 686 134 377 485 463  63 570 222 269 567 343 664 356 450 308
 500 744 557 629 449  88 316 156  60 195 455 132 566  84 720 139 376 326
 557 337 108 431 240 196 643 174 510 581]


In [ ]:
# flatten
data = np.array([
    [30,40,50],
    [60,70,80]
])
print(data.flatten())

[30 40 50 60 70 80]


In [ ]:
#operation between two arrays

a = np.array([65,75,85])

b = np.array([5,5,5])

print(a + b)
print(a * b)

[70 80 90]
[325 375 425]
